# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Graham Heimberg
tagline:          'personal webpage'
description:      'A computational biologist modeling gene expression in the immune system'
author:
name:           'Graham Heimberg'
url:            'www.grahamheimberg.com'
baseurl:        ''
#baseurl:        '/'

# Google Analytics
google_analytics: UA-121415295-1

# add comments
disqus:
  shortname: Graham

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.7.0
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:           gheimberg
twitter:          gheimberg

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
